name: eggcounting
channels:
  - conda-forge
  - defaults
dependencies:
  - fire
  - numpy
  - opencv
  - pandas
  - pyqt
  - pytables
  - python
  - tqdm
  - pip
  - scipy
  - scikit-image
  - scikit-learn
  - pip:
    - imgstore
